### ISSUE TITLE
Fails to start with servers.

### ISSUE THREAD

**Issue by AzureDoom** [BounceSMP/BounceStyles#4]
```
[20.03 01:23:59] [Server] [main/ERROR]: Failed to start the minecraft server
[20.03 01:23:59] [Server] java.lang.RuntimeExceptionCould not execute entrypoint stage 'main' due to errors, provided by 'bounce_styles'!
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] Caused byjava.lang.NoClassDefFoundError: net/minecraft/class_746
[20.03 01:23:59] [Server] 	at dev.bsmp.bouncestyles.BounceStyles.onInitialize(BounceStyles.java:28) ~[BounceStyles-1.18.2-2.0.0.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	... more
[20.03 01:23:59] [Server] Caused byjava.lang.ClassNotFoundException: net.minecraft.class_746
[20.03 01:23:59] [Server] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
[20.03 01:23:59] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[20.03 01:23:59] [Server] 	at dev.bsmp.bouncestyles.BounceStyles.onInitialize(BounceStyles.java:28) ~[BounceStyles-1.18.2-2.0.0.jar:?]
[20.03 01:23:59] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
[20.03 01:23:59] [Server] 	... more
```
Looks to be something related to your packet here https://github.com/BounceSMP/BounceStyles/blob/fabric/1.18/src/main/java/dev/bsmp/bouncestyles/BounceStyles.java#L28

It looks to be here: https://github.com/BounceSMP/BounceStyles/blob/fabric/1.18/src/main/java/dev/bsmp/bouncestyles/networking/SyncStyleUnlocksBi.java#L26

**Comment by RyanV97** [comment]
Little embarrassing that I made this mistake, but simple enough to fix. Will fix in my upcoming v2.1
