### ISSUE TITLE
/bouncestyles equip and wardrobe ui failure.

### ISSUE THREAD

**Issue by Bravo59** [BounceSMP/BounceStyles#6]
Specs:
Bounce SMP Pack 1.3
Survival Server
Running commands as OP

Repro:
1. Run command: /origin gui <player_name>, select human and any job.
2. Run command: /bouncestyles unlock <player_name> all.
3. Run command: /bouncestyles itemize bounce_styles:demon_horns_a <player_name>. This will give the player a bounce styles magazine for the demon horns.
4. run command /bouncestyles equip while holding the magazine. The command should error out with trace-back:
'Unknown or incomplete command, see below for error
/bouncestyles equip<--'
There is no additional autocomplete after equip.
5. Navigate to Options > Controls > Key Binds. Using the search bar at the bottom, search for 'wardrobe'. 
6. Set the 'Open Wardrobe UI' keybind to another key without conflicts (the default of "." conflicted).
7. Back in game press the new keybind. The wardrobe UI will not appear.
8. Repeat steps 4 - 7 in Creative mode if started in Survival or vice versa, neither work.

Expected outcome:
If a player has all bouncestyles unlocked for them, and the /bouncestyles equip command is run while they are holding a particular bounce styles magazine, that style will be applied to them without error. In addition, the wardrobe UI should be accessible to further manage the player styles.

**Comment by Bravo59** [comment]
The following traceback occurs in the server log when the 'wardrobe ui' key is pressed:

`java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "id" is null
        at dev.bsmp.bouncestyles.data.StyleData.unlocksToNBT(StyleData.java:197) ~[BounceStyles-Fabric-1.18.2-2.1.1.jar:?]
        at dev.bsmp.bouncestyles.data.StyleData.toNBT(StyleData.java:180) ~[BounceStyles-Fabric-1.18.2-2.1.1.jar:?]
        at dev.bsmp.bouncestyles.networking.SyncStyleUnlocksBi.toClientBuf(SyncStyleUnlocksBi.java:41) ~[BounceStyles-Fabric-1.18.2-2.1.1.jar:?]
        at dev.bsmp.bouncestyles.networking.SyncStyleUnlocksBi.sendToPlayer(SyncStyleUnlocksBi.java:32) ~[BounceStyles-Fabric-1.18.2-2.1.1.jar:?]
        at dev.bsmp.bouncestyles.networking.SyncStyleUnlocksBi.lambda$handleServer$1(SyncStyleUnlocksBi.java:28) ~[BounceStyles-Fabric-1.18.2-2.1.1.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by RyanV97** [comment]
Please Note: While I'm marking this as fixed, I was unable to actually reproduce the issue myself. That being said, I fixed what I believe to be the underlying issue that, at the very least, should allow you to continue using the Wardrobe UI if a null id is found for some reason.
